---
- name: Enable and Start Firewall
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open Required Ports for Master Node
  ansible.posix.firewalld:
    port: "{{item}}"
    immediate: true
    permanent: true
    state: enabled
  loop:
    - 6443/tcp
    - 2379-2389/tcp
    - 10250/tcp
    - 10259/tcp
    - 10257/tcp
  when: inventory_hostname in groups['master']
    
- name: Open Required Ports for Master Node
  ansible.posix.firewalld:
    port: "{{item}}"
    immediate: true
    permanent: true
    state: enabled
  loop:
    - 10250/tcp
    - 10256/tcp
    - 30000-32767/tcp
  when: inventory_hostname in groups['worker']      
