---
  - name: Downloading Solr
    ansible.builtin.get_url:
      url: https://www.apache.org/dyn/closer.lua/solr/solr/9.7.0/solr-9.7.0.tgz?action=download
      dest: "{{download_dir}}/solr-{{solr_version}}.tgz"
      checksum: "{{ solr_checksum }}"
      timeout: 120


  - name: Extract Solr
    ansible.builtin.unarchive:
      src: "{{download_dir}}/solr-{{solr_version}}.tgz"
      dest: "{{download_dir}}"
      remote_src: true
      creates: "{{download_dir}}/solr-{{solr_version}}/README.txt"


