---
- name: Playbook to Deploy a Kubernetes Cluster
  hosts: all
  
  pre_tasks:
    - name: Install Required Services and Utilites 
      ansible.builtin.dnf:
        name: "{{item}}"
        state: present
      loop:
        - firewalld
        - 'dnf-command(versionlock)'
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python3
        - python3-pip
        - python3-setuptools

  roles:
    - firewall
    - system_setup
    - k8s_utilities
    - container_runtime
    - kubeadm

