---
- name: Disable Swap Immediatly
  ansible.builtin.command: swapoff -a 

- name: Disable Swap Permanently
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s)'
    line: '# \1'

- name: Disable SELINUX Immediatly
  ansible.builtin.command: setenforce 0

- name: Disable SELINUX Permanently
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'

- name: Enable Required Kernel Modules
  ansible.builtin.blockinfile:
    path: /etc/modules-load.d/k8s.conf
    block: |
      overlay
      br_netfilter
    state: present
    create: true

- name: Enable Required Kernel Modules
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    state: present
    create: true

- name: Deploy the changes
  ansible.builtin.shell: |
    modprobe overlay
    modprobe br_netfilter
    sysctl --system