---

      - name: Install Apache and Firewall
        ansible.builtin.package:
          name: "{{ item }}"
          state: present
        loop:
            - "{{ firewall_package }}"
            - "{{ apache_package }}"

