---
# tasks file for first_role

      - name: Install Apache and Firewall
        ansible.builtin.package:
          name: "{{ item }}"
          state: present
        loop:
            - "{{ firewall_package }}"
            - "{{ apache_package }}"

      - name: Make sure Apache and Firewall is running
        ansible.builtin.service:
          name: "{{ item }}"
          state: started
          enabled: true
        loop:
          - "{{ firewall_package }}"
          - "{{ apache_package }}"

